### ISSUE TITLE
Please change the name of this GitHub Repository

### ISSUE THREAD

**Issue by jjasghar** [IBM/fdisk#2]
`fdisk` is a well-known Linux application.

Please change the name to `libfdisk` or `rust-fdisk` or whatever the `rust` convention is for libraries.

Thank you.

/cc @stevemar @christo4ferris

**Comment by jjasghar** [comment]
Please change this repository name.

**Comment by jjasghar** [comment]
I will change this repositories name by the end of the week if you don't. 2020-05-08

**Comment by christo4ferris** [comment]
+1 changing the name won't break any links or forks, but we really should use a different name here to avoid confusion.

**Comment by jjasghar** [comment]
renamed to `fdisk-lib` per the Rust conventions

**Comment by jjasghar** [comment]
Please rename this repository. ‘frisk’ is a well known Linux/Unix application

**Comment by jjasghar** [comment]
@christo4ferris @stevemar they haven't changed the name of this repo, can i go ahead and change (just the repo name) to something like `fdisk-lib` or `fdisk-rs`?

**Comment by christo4ferris** [comment]
Yeah

Chris

**Comment by jjasghar** [comment]
Renamed.
